name: telco-churn
channels:
  - conda-forge
  - defaults
dependencies:
# --- CONDA MANAGED ---
  - python=3.10.19
  - pip=25.3
  # --- CORE DATA PROCESSING ---
  - numpy=2.2.5
  - pandas=2.3.3
  - scipy=1.15.3
    # --- MACHINE LEARNING & MODELING ---
  - scikit-learn=1.7.2
  - imbalanced-learn=0.14.0
  - xgboost=3.1.2
  - joblib=1.5.2
  # --- EXPERIMENT TRACKING & UTILS ---
  - mlflow=3.6.0
  - loguru=0.7.3
  - python-dotenv=1.2.1
  - tqdm=4.67.1
  # --- VISUALIZATION ---
  - matplotlib=3.10.0
  - umap-learn=0.5.9.post2
  # --- QUALITY TOOLS ---
  - pytest=9.0.1
  # --- WEB APP / DASHBOARD ---
  - streamlit=1.52.2

# --- PIP MANAGED ---
  - pip:
      # --- PROJECT ---
      - -e .